CREATE TABLE users (
    id TEXT PRIMARY KEY NOT NULL,
    github_id BIGINT NOT NULL UNIQUE,
    github_login TEXT NOT NULL,
    avatar_url TEXT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE oauth_login_states (
    state_hash TEXT PRIMARY KEY NOT NULL,
    expires_at BIGINT NOT NULL,
    return_to TEXT
);

CREATE TABLE sessions (
    token_hash TEXT PRIMARY KEY NOT NULL,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at BIGINT NOT NULL,
    created_at BIGINT NOT NULL
);

CREATE INDEX sessions_user_id_idx ON sessions (user_id);
CREATE INDEX sessions_expires_at_idx ON sessions (expires_at);

CREATE TABLE cli_authorization_requests (
    id TEXT PRIMARY KEY NOT NULL,
    user_code TEXT NOT NULL UNIQUE,
    poll_secret_hash TEXT NOT NULL,
    approval_secret_hash TEXT NOT NULL,
    device_name TEXT NOT NULL,
    created_at BIGINT NOT NULL,
    expires_at BIGINT NOT NULL,
    approved_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    approved_at BIGINT,
    completed_at BIGINT
);

CREATE INDEX cli_authorization_requests_expires_at_idx
    ON cli_authorization_requests (expires_at);

CREATE TABLE cli_sessions (
    id TEXT PRIMARY KEY NOT NULL,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_name TEXT NOT NULL,
    refresh_token_hash TEXT NOT NULL UNIQUE,
    created_at BIGINT NOT NULL,
    last_used_at BIGINT NOT NULL,
    expires_at BIGINT NOT NULL,
    revoked_at BIGINT
);

CREATE INDEX cli_sessions_user_id_idx ON cli_sessions (user_id);

CREATE TABLE cli_used_refresh_tokens (
    token_hash TEXT PRIMARY KEY NOT NULL,
    session_id TEXT NOT NULL REFERENCES cli_sessions(id) ON DELETE CASCADE,
    used_at BIGINT NOT NULL
);

CREATE TABLE cli_access_tokens (
    token_hash TEXT PRIMARY KEY NOT NULL,
    session_id TEXT NOT NULL REFERENCES cli_sessions(id) ON DELETE CASCADE,
    expires_at BIGINT NOT NULL,
    created_at BIGINT NOT NULL
);

CREATE INDEX cli_access_tokens_expires_at_idx ON cli_access_tokens (expires_at);

CREATE TABLE publish_jobs (
    id TEXT PRIMARY KEY NOT NULL,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    idempotency_key TEXT NOT NULL,
    state TEXT NOT NULL CHECK (
        state IN (
            'uploading',
            'queued',
            'verifying',
            'admitted',
            'rejected',
            'purged',
            'expired',
            'failed'
        )
    ),
    archive_format TEXT NOT NULL,
    declared_size_bytes BIGINT NOT NULL CHECK (declared_size_bytes > 0),
    declared_sha256 TEXT NOT NULL,
    upload_object_key TEXT NOT NULL UNIQUE,
    intake_object_key TEXT NOT NULL UNIQUE,
    upload_expires_at BIGINT NOT NULL,
    upload_generation BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    queued_at BIGINT,
    failure_code TEXT,
    verification_claim TEXT,
    verification_started_at BIGINT,
    actual_size_bytes BIGINT,
    actual_sha256 TEXT,
    admitted_at BIGINT,
    private_purged_at BIGINT,
    public_trace_object_key TEXT,
    public_trace_size_bytes BIGINT,
    public_trace_sha256 TEXT,
    public_stamp_object_key TEXT,
    public_stamp_size_bytes BIGINT,
    public_stamp_sha256 TEXT,
    UNIQUE (user_id, idempotency_key)
);

CREATE INDEX publish_jobs_user_created_idx
    ON publish_jobs (user_id, created_at DESC);
CREATE INDEX publish_jobs_state_updated_idx
    ON publish_jobs (state, updated_at);
CREATE INDEX publish_jobs_upload_expiry_idx
    ON publish_jobs (upload_expires_at)
    WHERE state = 'uploading';
CREATE UNIQUE INDEX publish_jobs_verification_claim_idx
    ON publish_jobs (verification_claim)
    WHERE verification_claim IS NOT NULL;
CREATE INDEX publish_jobs_public_idx
    ON publish_jobs (admitted_at DESC)
    WHERE state = 'admitted';
CREATE INDEX publish_jobs_claim_queue_idx
    ON publish_jobs (queued_at, id)
    WHERE state = 'queued';

CREATE TABLE publication_metadata (
    publication_id TEXT PRIMARY KEY NOT NULL REFERENCES publish_jobs(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    tags_json TEXT NOT NULL,
    title_source TEXT NOT NULL CHECK (title_source IN ('generated', 'fallback')),
    generator_model TEXT,
    generator_prompt_version TEXT,
    generated_at BIGINT,
    last_generation_attempt_at BIGINT,
    updated_at BIGINT NOT NULL,
    generation_claim TEXT,
    generation_claimed_at BIGINT
);

CREATE INDEX publication_metadata_generated_idx
    ON publication_metadata (title_source, last_generation_attempt_at);
CREATE INDEX publication_metadata_claim_idx
    ON publication_metadata (generation_claimed_at)
    WHERE generation_claim IS NOT NULL;

CREATE TABLE publication_activity_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publication_id TEXT NOT NULL REFERENCES publish_jobs(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL,
    subject_key_sha256 TEXT NOT NULL,
    occurred_at BIGINT NOT NULL,
    UNIQUE (publication_id, event_type, subject_key_sha256)
);

CREATE INDEX publication_activity_events_recent_idx
    ON publication_activity_events (event_type, occurred_at DESC, publication_id);

CREATE TABLE library_metadata_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_start BIGINT NOT NULL,
    model TEXT NOT NULL,
    prompt_tokens BIGINT NOT NULL CHECK (prompt_tokens >= 0),
    cached_prompt_tokens BIGINT NOT NULL CHECK (cached_prompt_tokens >= 0),
    cache_write_tokens BIGINT NOT NULL CHECK (cache_write_tokens >= 0),
    completion_tokens BIGINT NOT NULL CHECK (completion_tokens >= 0),
    estimated_cost_nanousd BIGINT NOT NULL CHECK (estimated_cost_nanousd >= 0),
    created_at BIGINT NOT NULL
);

CREATE INDEX library_metadata_usage_period_idx
    ON library_metadata_usage (period_start, created_at DESC);
