CREATE TABLE publication_metadata (
    publication_id TEXT PRIMARY KEY NOT NULL REFERENCES publish_jobs(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    tags_json TEXT NOT NULL,
    title_source TEXT NOT NULL CHECK (title_source IN ('generated', 'fallback')),
    generator_model TEXT,
    generator_prompt_version TEXT,
    generated_at BIGINT,
    last_generation_attempt_at BIGINT,
    updated_at BIGINT NOT NULL
);

CREATE INDEX publication_metadata_generated_idx
    ON publication_metadata (title_source, last_generation_attempt_at);

CREATE TABLE publication_activity_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publication_id TEXT NOT NULL REFERENCES publish_jobs(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL,
    subject_key_sha256 TEXT NOT NULL,
    occurred_at BIGINT NOT NULL,
    UNIQUE (publication_id, event_type, subject_key_sha256)
);

CREATE INDEX publication_activity_events_recent_idx
    ON publication_activity_events (event_type, occurred_at DESC, publication_id);
