CREATE TABLE library_metadata_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_start BIGINT NOT NULL,
    model TEXT NOT NULL,
    prompt_tokens BIGINT NOT NULL CHECK (prompt_tokens >= 0),
    cached_prompt_tokens BIGINT NOT NULL CHECK (cached_prompt_tokens >= 0),
    cache_write_tokens BIGINT NOT NULL CHECK (cache_write_tokens >= 0),
    completion_tokens BIGINT NOT NULL CHECK (completion_tokens >= 0),
    estimated_cost_nanousd BIGINT NOT NULL CHECK (estimated_cost_nanousd >= 0),
    created_at BIGINT NOT NULL
);

CREATE INDEX library_metadata_usage_period_idx
    ON library_metadata_usage (period_start, created_at DESC);
