ALTER TABLE users
    ADD COLUMN service_plan TEXT NOT NULL DEFAULT 'free'
        CHECK (service_plan IN ('free', 'paid_preview'));

CREATE TABLE notary_admission_tickets (
    token_hash TEXT PRIMARY KEY NOT NULL,
    subject_id TEXT REFERENCES users(id) ON DELETE CASCADE,
    access_pool TEXT NOT NULL CHECK (access_pool IN ('public', 'free', 'paid_preview')),
    mode TEXT NOT NULL CHECK (mode IN ('capture', 'finalize')),
    directory_generation BIGINT NOT NULL CHECK (directory_generation >= 0),
    record_digest TEXT,
    requested_allowance_bytes BIGINT NOT NULL CHECK (requested_allowance_bytes > 0),
    session_timeout_secs BIGINT NOT NULL CHECK (session_timeout_secs > 0),
    max_attestable_http_bytes BIGINT NOT NULL CHECK (max_attestable_http_bytes > 0),
    max_frame_bytes BIGINT NOT NULL CHECK (max_frame_bytes > 0),
    max_private_chunk_bytes BIGINT NOT NULL CHECK (max_private_chunk_bytes > 0),
    max_private_chunk_commitments BIGINT NOT NULL CHECK (max_private_chunk_commitments > 0),
    issued_at BIGINT NOT NULL,
    expires_at BIGINT NOT NULL,
    consumed_at BIGINT,
    consumed_by_instance TEXT,
    lease_id TEXT,
    CHECK (
        (mode = 'capture' AND record_digest IS NULL)
        OR (mode = 'finalize' AND record_digest IS NOT NULL)
    )
);

CREATE INDEX notary_admission_tickets_expiry_idx
    ON notary_admission_tickets (expires_at);
CREATE INDEX notary_admission_tickets_subject_issued_idx
    ON notary_admission_tickets (subject_id, issued_at DESC);
CREATE INDEX notary_admission_tickets_public_issued_idx
    ON notary_admission_tickets (issued_at DESC)
    WHERE subject_id IS NULL;

CREATE TABLE notary_admission_leases (
    id TEXT PRIMARY KEY NOT NULL,
    notary_instance_id TEXT NOT NULL,
    subject_id TEXT REFERENCES users(id) ON DELETE CASCADE,
    access_pool TEXT NOT NULL CHECK (access_pool IN ('public', 'free', 'paid_preview')),
    mode TEXT NOT NULL CHECK (mode IN ('capture', 'finalize')),
    acquired_at BIGINT NOT NULL,
    expires_at BIGINT NOT NULL,
    released_at BIGINT,
    terminal_state TEXT CHECK (terminal_state IN ('released', 'expired'))
);

CREATE INDEX notary_admission_leases_active_idx
    ON notary_admission_leases (mode, access_pool, expires_at)
    WHERE released_at IS NULL;
CREATE INDEX notary_admission_leases_subject_active_idx
    ON notary_admission_leases (subject_id, mode, expires_at)
    WHERE released_at IS NULL AND subject_id IS NOT NULL;

CREATE TABLE notary_finalization_credit_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    budget_subject TEXT NOT NULL,
    account_id TEXT REFERENCES users(id) ON DELETE CASCADE,
    record_digest TEXT NOT NULL,
    allowance_bytes BIGINT NOT NULL CHECK (allowance_bytes > 0),
    period_start BIGINT NOT NULL,
    created_at BIGINT NOT NULL,
    UNIQUE (budget_subject, record_digest)
);

CREATE INDEX notary_finalization_credit_period_idx
    ON notary_finalization_credit_ledger (budget_subject, period_start, created_at);
